### ISSUE TITLE
please add a / between mdpi and hdpi

### ISSUE THREAD

**Issue by misterfifi1** [androhi/AndroidDrawableViewer#16]
Please check the screenshot attached

<img width="347" alt="screen shot 2016-05-03 at 09 47 15" src="https://cloud.githubusercontent.com/assets/5573438/14977441/2a1a2a8e-1114-11e6-904d-8cbd1f1169ca.png">

**Comment by androhi** [comment]
Thank you for creating the issue.
So your comment is right, I'll fix it.

**Comment by shiraji** [comment]
Check #12

**Comment by androhi** [comment]
@shiraji Thank you so much! Sorry, I had forgot.
I'm going to release during a few days.

**Comment by androhi** [comment]
@misterfifi1 I'm sorry for late release. I release today.
