### ISSUE TITLE
how to user this feature ?

### ISSUE THREAD

**Issue by captainJeck** [androhi/AndroidDrawableViewer#17]
I have installed the plugin, open DrawableViewer, but nothing to show ?

**Comment by androhi** [comment]
@captainJeck I'm sorry. My reply was so late.
Please follow the picture and try the setting.

![resource_settings](https://cloud.githubusercontent.com/assets/1404787/15294612/fd9c6fc6-1bc7-11e6-8771-ddf0763c7dcc.png)

**Comment by captainJeck** [comment]
not effective in Android Studio 2.1
![2016-05-17 20-08-39](https://cloud.githubusercontent.com/assets/3256708/15321910/1cc2e5a2-1c6c-11e6-9a02-0f011e230729.png)

**Comment by androhi** [comment]
oh...
I'm using Android Studio 2.1, too. But it doesn't happen to me.
If another cause, I guess the drawable folder name is unintended.
For example, are they `drawable-xdpi` , `drawable-xxhdpi` or `drawable-xxxhdpi` ?

**Comment by androhi** [comment]
@captainJeck I released ver2.1. So please update the plugin.
