### ISSUE TITLE
Allow user to add their own drawable folder qualifiers

### ISSUE THREAD

**Issue by Cliabhach** [androhi/AndroidDrawableViewer#18]
Right now I can't make the plugin show the contents of `drawable-nodpi`, `drawable-v21`, `drawable`, or `drawable-en` folders.

Would it make sense for the plugin to have a list of qualifiers found in that directory, which could be enabled or disabled below? Or maybe just have a list of directory names that are added on to the list?

**Comment by androhi** [comment]
I'm sorry for late reply. I want to show the all drawable folders, so I will improve it.

**Comment by androhi** [comment]
I supported all drawable directories with [this PR](https://github.com/androhi/AndroidDrawableViewer/pull/20).
I will release as version 3.0.
